import os
import traceback  
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from langchain_core.messages import HumanMessage
from src.graph import build_graph  

app = FastAPI(title="Multi-Agent AI Orchestration API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

try:
    graph = build_graph()
    print("✅ LangGraph compiled and built successfully in server.py")
except Exception as graph_err:
    print("❌ CRITICAL ERROR DURING GRAPH COMPILATION:")
    print(traceback.format_exc())
    graph = None

class OrchestratorRequest(BaseModel):
    context_data: str
    objective: str

@app.get("/", response_class=HTMLResponse)
async def read_root():
    try:
        with open("templates/index.html", "r", encoding="utf-8") as f:
            return HTMLResponse(content=f.read(), status_code=200)
    except FileNotFoundError:
        return HTMLResponse(content="<h1>templates/index.html not found</h1>", status_code=404)

@app.post("/api/analyze")
async def analyze_data(payload: OrchestratorRequest):
    if graph is None:
        raise HTTPException(status_code=500, detail="LangGraph pipeline is uninitialized.")
        
    try:
        compiled_prompt = f"Data:\n{payload.context_data}\n\nObjective:\n{payload.objective}"
        
        initial_state = {
            "messages": [HumanMessage(content=compiled_prompt)],
            "next_step": "Supervisor",
            "confidence_score": 1.0,
            "requires_approval": False
        }
        
        print("\n=== 🚀 Graph Invocation Started ===")
        result = graph.invoke(initial_state)
        print("=== ✅ Graph Invocation Finished ===")
        
        if "messages" in result and len(result["messages"]) > 0:
            final_output = result["messages"][-1].content
        else:
            final_output = "No clear analysis was generated by the agents."
        
        return {
            "status": "success",
            "final_analysis": final_output,
            "confidence": result.get("confidence_score", 1.0)
        }
    except Exception as e:
        print("\n❌❌❌ CRITICAL BACKEND EXCEPTION CAUGHT IN /api/analyze ❌❌❌")
        print(traceback.format_exc()) 
        raise HTTPException(status_code=500, detail=str(e))